version: "1"
services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pvsDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
  
  jaeger:
    image: jaegertracing/all-in-one:1.6
    ports: 
     - 16686:16686
     - 14268:14268
     - 5778:5778
    environment:
     COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  nginx:
    image: thisisatest/nginx
    build:
      context : nginxbuilding
      dockerfile: ./Dockerfile
    ports:
      - 6969:80

volumes:
  postgres_data:
     